#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
#       2018    Elvis Yao <ElvisCW.Yao@moxa.com>
#       2018    Ken CJ Chou <KenCJ.Chou@moxa.com>
#

rfs_resize() {
	expand2fs
	mv /sbin/expand2fs /sbin/expand2fs.bak
	sync
	/sbin/reboot -d -f -i
}

init_gpio() {
	local gpio=${1}
	local direction=${2}
	local value=${3}

	if [ ! -e "/sys/class/gpio/gpio${gpio}" ]; then
		echo "${gpio}" > /sys/class/gpio/export
	fi

	if [ "${direction}" = "in" ]; then
		echo "in" > /sys/class/gpio/gpio${gpio}/direction
	elif [ "${direction}" = "out" ]; then
		if [ "${value}" = "0" ]; then
			echo "low" > /sys/class/gpio/gpio${gpio}/direction
		elif [ "${value}" = "1" ]; then
			echo "high" > /sys/class/gpio/gpio${gpio}/direction
		fi
	fi
}

get_model_name() {
	local model_name="$(mx-ver -m | awk '{print $1}')"

	case ${model_name} in
	UC-5101-LX|UC-5101-T-LX)
		echo "UC-5101-LX"
		;;
	UC-5102-LX|UC-5102-T-LX)
		echo "UC-5102-LX"
		;;
	UC-5111-LX|UC-5111-T-LX)
		echo "UC-5111-LX"
		;;
	UC-5112-LX|UC-5112-T-LX)
		echo "UC-5112-LX"
		;;
	esac
}

initial_dio() {
	init_gpio "54" "out" "0"
	init_gpio "55" "out" "0"
	init_gpio "56" "out" "0"
	init_gpio "57" "out" "0"
	init_gpio "86" "in"
	init_gpio "87" "in"
	init_gpio "88" "in"
	init_gpio "89" "in"
}

initial_tpm2() {
	local tpm2="$(fw_printenv -n tpm2 2>/dev/null)"

	if [ "${tpm2}" = "1" ]; then
		export TPM2TOOLS_TCTI_NAME=device
		export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0
		modprobe tpm_tis_spi
	fi
}

uc5100_initial() {
	local model_name=$(get_model_name)

	ln -sf /etc/moxa-configs/${model_name}/configs/* /etc/moxa-configs/
	ln -sf /etc/moxa-configs/${model_name}/udev/* /etc/udev/rules.d/

	# only needs to initial one time
	if [ -f /sbin/expand2fs ]; then
		# Enable bootloader to pass the fsck.repair parameter to kernel
		fw_setenv robust 1
		rfs_resize
	fi

	# general initial
	initial_dio
	initial_tpm2

	# light up system ready led
	mx-led-ctl -p 1 -i 1 on
}

umount_rfs() {
	umount -f -l /tmp
        umount -f -l /home
        umount -f -l /media
        umount -f -l /mnt
        umount -f -l /etc
        umount -f -l /root
        umount -f -l /opt
        umount -f -l /usr
        umount -f -l /bin
        umount -f -l /sbin
        umount -f -l /var
        umount -f -l /lib
        umount -f -l /overlayfs
}

uc5100_stop() {
	local model_name=$(get_model_name)

	case ${model_name} in
	UC-5101-LX|UC-5111-LX)
		;;
	UC-5102-LX|UC-5112-LX)
		cell_mgmt stop
		wifi_mgmt stop
		if lsmod | grep "^wlan" -q; then
			rmmod wlan
		fi
		mx-module-ctl -s 1 -p off
		;;
	*)
		echo "Error: Unknown model name" >&2
		;;
	esac

	# general stop	
	umount_rfs
}

case "$1" in
start)
	uc5100_initial
	;;
restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
stop)
	uc5100_stop
	;;
*)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
exit 0
